### ISSUE TITLE
Tip to escape from staff

### ISSUE THREAD

**Issue by MiClobiMC** [b7c/b7.Xabbo#1]
When the module detects a staff execute this hash {out:Quit}

**Comment by b7c** [comment]
`Quit` will make your avatar walk out the door, the escape component sends `FlatOpc` (`OpenFlatConnection` in Flash), a request to enter a non-existing room (with id 0) which removes your avatar from the room instantly.
https://github.com/b7c/b7.Xabbo/blob/75653cfdbe965b6f1dd047ab3cb860e696de36d9/b7.Xabbo/Components/General/EscapeComponent.cs#L96
